### ISSUE TITLE
Feed failing (silently)

### ISSUE THREAD

**Issue by alecisec** [PromoFaux/MattermostRSS#6]
**Testing with the following config :** 

{
  "BotCheckIntervalMs": 30000,
  "MattermostWebhookUrl": "https://domain/hooks/m4cckh6a4pg",
  "BotChannelDefault": "testing",
  "BotNameDefault": "bot",
  "BotImageDefault": "https://domain/icon.png",
  "RssFeeds": [
    {
      "FeedPretext": "Schneier on Security",
      "Url": "https://www.schneier.com/blog/atom.xml",
      "BotChannelOverride": "",
      "BotNameOverride": "Bruce Schneier",
      "BotImageOverride": "https://www.schneier.com/images/bruce-blog3.jpg",
      "IncludeContent": false
    },
    {
      "FeedPretext": "Threat post",
      "Url": "https://threatpost.com/feed/",
      "BotChannelOverride": "",
      "BotNameOverride": "Threat post",
      "BotImageOverride": "https://threatpost.com/wp-content/themes/threatpost/images/site-icon.png",
      "IncludeContent": false
    },
    {
      "FeedPretext": "Blog",
      "Url": "https://feeds.feedburner.com/TroyHunt",
      "BotChannelOverride": "",
      "BotNameOverride": "Troy Hunt",
      "BotImageOverride": "https://www.troyhunt.com/favicon.png",
      "IncludeContent": false
    },
    {
      "FeedPretext": "Krebs on Security",
      "Url": "https://krebsonsecurity.com/feed/",
      "BotChannelOverride": "",
      "BotNameOverride": "Brian Krebs",
      "BotImageOverride": "https://krebsonsecurity.com/wp-content/uploads/2009/11/krebsinbelgium.png",
      "IncludeContent": false
    },
    {
      "FeedPretext": "Naked Security",
      "Url": "https://nakedsecurity.sophos.com/feed/",
      "BotChannelOverride": "",
      "BotNameOverride": "Sophos",
      "BotImageOverride": "https://pbs.twimg.com/profile_images/667033512403476480/HPSTaLj2_200x200.png",
      "IncludeContent": false
    },
    {
      "FeedPretext": "Bulletins",
      "Url": "https://www.auscert.org.au/rss/bulletins/",
      "BotChannelOverride": "",
      "BotNameOverride": "AusCERT",
      "BotImageOverride": "https://pbs.twimg.com/profile_images/476961139285184513/cws56Xhp.png",
      "IncludeContent": false
    }
  ],
  "RedditJsonFeeds": null
}

**I've concluded that all feeds read correctly except the last in the list - no errors are produced unfortunately. All other feeds correctly read and append a  "LastProcessedItem" flag/timestamp.
I did note however inconsistency in the "Z" on the end of the timestamp, sometimes it had a preceding space and I was unsure of the reason for that character having been appended.**

**Comment by PromoFaux** [comment]
Thanks for the detailed report, I will look into this as soon as I can

**Comment by PromoFaux** [comment]
Verified. I actually have this feed in my config, and I've not seen it appear on mattermost since 1.1

**Comment by alecisec** [comment]
Is the appended "Z" deliberate?

**Comment by PromoFaux** [comment]
The Z means it's UTC (Zulu, I believe), and is what is returned from the [3rd library I'm using](https://github.com/codehollow/FeedReader/blob/83e198c906de3955ef6c5066608cc68c8fe9a41b/FeedReader/Helpers.cs#L67-L91). I don't think it makes a difference, as it's always read fine.

Not had a chance to play with your config yet, but hopefully will get some time over the weekend!

**Comment by PromoFaux** [comment]
```XML
<item>
	<title>ESB-2017.2517 - [Appliance] HPE Intelligent Management Center (iMC) PLAT: Execute arbitrary code/commands - Remote with user interaction</title>
	<link>http://www.auscert.org.au/bulletins/53182</link>
	<description>&lt;pre&gt;-----BEGIN PGP SIGNED MESSAGE------END PGP SIGNATURE-----(truncated)</description>
	<guid>http://www.auscert.org.au/bulletins/53182</guid>
</item>
```

That last one is failing because the items do not have a published date. If there is no published date, then that item is skipped, as I have no frame of reference as to whether the item has been processed on a past run.

Interestingly, it also bungs ALL of the content into the `<description>` tag, which is a bit cheeky. I could be wrong (I often am), but that will break my `includeContent` flag.

```c#
 Text = converter.Convert(rssFeed.IncludeContent ? rss20FeedItem.Content ?? rss20FeedItem.Description ?? ""  : rss20FeedItem.Description ?? ""),
```

That one-liner basically says (in pseudo-code):
```
if (User wants to include content)
{
	if (item has content)
  {
  	  post content
  }
  else if (item has description but not content)
  {
  	post description in lieu of content
  }
  else (item has neither content or description)
  {
  	post empty string
  }
}
else
{
	if (item has description)
	{
		post description
	}
	else
	{
		post empty string
	}
}
```

**Comment by PromoFaux** [comment]
as with #7, it looks like there is an issue with two of the feeds in this list, and I'm not sure it is necessarily a bug on this end. 

"https://www.auscert.org.au/rss/bulletins/" could do with including a processed date, unless I can think of another way to determine whether or not an item has been processed...

**Comment by alecisec** [comment]
I'll suggest it to them, thanks for determining the issue

**Comment by PromoFaux** [comment]
_(offtopic: I've moved the docker repo to `promofaux/matterfeed.net`, so you'll need to change it on your end, too._

**Comment by alecisec** [comment]
It seems they may not to modify the pubDate field. While I'd agree that your system of using the most recent pubDate timestamp seems more elegant would there be any other way to do it? I assume more complex RSS readers would keep a local DB and reference that for duplicates. I'm not sure how the bitbackofen (https://github.com/bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost) implementation works but that has other issues which prevent us using it.

**Comment by PromoFaux** [comment]
Heh, The whole reason I started this project was because I couldn't get that one working myself.

Looks like it uses last title, rather than publish time... so maybe there is something I can do there.. Will have a think on it!

**Comment by PromoFaux** [comment]
Hmmm, looking at the other one in more detail... I am not sure I like how it's working. It seems that it fetches the feed, and only ever posts whatever [feed item is at position 0](https://github.com/bitbackofen/Rss-Atom-Feed-Integration-for-Mattermost/blob/master/feedfetcher.py#L133) (providing the title has changed since the last time it checked).

I much prefer the idea of checking through all posts in the feed as there could be more than one new post per feed, what is the sense of downloading the whole thing we're only going to process one item? :)

A local DB seems a bit OTT, but not beyond the realms of possibility I guess...

Another thought I have is to save a copy of each feed locally, and use it to compare when grabbing a new copy. Lots of thoughts....

**Comment by PromoFaux** [comment]
@alecisec If you like, you can check out the `development` branch locally... (or use promofaux/matterfeed.net:development` if you're using the docker cloud images) 

I've made some changes that I'm pretty sure will solve your issue.

I've introduced a `FallbackMode` flag to the RSS feed configs. If it is set to `true`, then each time the feed is downloaded, it will be saved to the directory that contains `secrets.json`, and used for comparison on the next download. You could do this will all of them, to be fair, but I've defaulted it to false to save unnecessary storage

```JSON
  "RssFeeds": [
    {
      "FallbackMode": false,
      "FeedPretext": "",
      "Url": "https://www.auscert.org.au/rss/bulletins/",
      "BotChannelOverride": "atests",
      "BotNameOverride": "AusCERT Bulletins",
      "BotImageOverride": "https://pbs.twimg.com/profile_images/476961139285184513/cws56Xhp_400x400.png",
      "IncludeContent": false,
      "LastProcessedItem": ""
    }
```

**Comment by alecisec** [comment]
Will check out the dev branch. I'd certainly say your code is closer to something I could run in production. For whatever reason the other one mentioned just randomly misses posts and I've never really tried to look into why. Just curious which <data> does the "IncludeContent" flag toggle display of?

**Comment by alecisec** [comment]
Okay so this is weird - I tried fallback mode just to see what happens - the result was it just scrubed the line from the json - no rss dump is made, the timestamp is written against the lastprocesseditem but the whole fallback line disappears without a trace. have tried a couple more times with the same result (definitely the dev branch and no errors were thrown in the logs)

**Comment by PromoFaux** [comment]
Hmmm, that's odd.. I'm using it myself on a couple. Are you 100% certain it's the dev branch?

Can you try the prebuilt docker image `promofaux/matterfeed.net:development` and see if that does the same thing... (it shouldn't)

**Comment by PromoFaux** [comment]
>Just curious which does the "IncludeContent" flag toggle display of?

Some feeds send the entire article as well as a short description. Some (like AusCERT) put the entire article inside the description feed (which is very annoying). By default, the full article is sent to mattermost (if it exists), otherwise the description is sent (provided it is not more than 500 chars).

If you add AusCERT to your lists and run it wiout the `IncludeContent` switch set to `false`, then some of their posts can get very long.

**Comment by PromoFaux** [comment]
@alecisec Did you get a chance to try the development tag of the prebuilt docker image? Seems to be working as far as I can tell...

**Comment by PromoFaux** [comment]
Closing due to lack of response. Issue appears to be fixed in latest release
