### ISSUE TITLE
(Non-Fatal) error processing feed

### ISSUE THREAD

**Issue by alecisec** [PromoFaux/MattermostRSS#7]
Response from logs as follows:

Feed Title: Troy Hunt's Blog
FeedType: RSS 2.0
Generator: Ghost 1.11

Problem retrieving feed
 Exception Message: '', hexadecimal value 0x1F, is an invalid character. Line 1, position 1.
One or more errors occurred. (Object reference not set to an instance of an object.)

This is from the feed https://feeds.feedburner.com/TroyHunt

The feed still seems to process OK however. I've seen a variation of this error which looked more like just "invalid character. Line 1, position 1.
One or more errors occurred. (Object reference not set to an instance of an object.)" ie it didn't state the character that had caused the error.

**Comment by PromoFaux** [comment]
Verified. I actually have this feed in my config, and I've not seen it appear on mattermost since 1.1 (though haven't had the time to check the logs!)

**Comment by PromoFaux** [comment]
Do you still get the same results if you specify XML format on the URL?

https://feeds.feedburner.com/TroyHunt?format=xml

**Comment by alecisec** [comment]
Yea first thing I tried was forcing the XML, produced the same error. It's still logging the same error this morning, but I can confirm the most recent post from the feed was successfully posted ~15 hrs ago and the  container has not rebooted for 17 hrs

**Comment by PromoFaux** [comment]
OK, just improved my logging a little, and it turns out the error is actually from the "Krebs on Security" feed. Though I am unable to work out so far whether this is an issue with the feed itself, or with the Library I am using... I will investigate further

```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
realpath(): Invalid argument
realpath(): Invalid argument
realpath(): Invalid argument
10/06/2017 19:12:00 - Application Started.

10/06/2017 19:12:01
Fetching URL: https://www.schneier.com/blog/atom.xml
Feed Type: Atom
Feed Title: Schneier on Security
Generator: Movable Type Pro
Processed 10/10 items. (0 previously processed or do not include a publish date)

10/06/2017 19:12:13
Fetching URL: https://threatpost.com/feed/
Feed Type: Rss 2.0
Feed Title: Threatpost | The first stop for security news
Generator: https://wordpress.org/?v=4.8.2
Processed 10/10 items. (0 previously processed or do not include a publish date)

10/06/2017 19:12:24
Fetching URL: https://feeds.feedburner.com/TroyHunt
Feed Type: Rss 2.0
Feed Title: Troy Hunt's Blog
Generator: Ghost 1.11
Processed 15/15 items. (0 previously processed or do not include a publish date)
The thread 1978 has exited with code 0 (0x0).
Exception thrown: 'System.Xml.XmlException' in System.Private.CoreLib.dll

10/06/2017 19:12:41
Fetching URL: https://krebsonsecurity.com/feed/
Unable to get feed. Exception: '', hexadecimal value 0x1F, is an invalid character. Line 1, position 1.

10/06/2017 19:12:42
Fetching URL: https://nakedsecurity.sophos.com/feed/
Feed Type: Rss 2.0
Feed Title: Naked Security
Generator: http://wordpress.com/
Processed 10/10 items. (0 previously processed or do not include a publish date)

10/06/2017 19:12:53
Fetching URL: https://www.auscert.org.au/rss/bulletins/
Feed Type: Rss 2.0
Feed Title: Security Bulletins
Generator:
Processed 0/20 items. (20 previously processed or do not include a publish date)
```

**Comment by PromoFaux** [comment]
OK, just tried this several other ways, and it is [definitely an issue with that feed](http://www.feedbucket.com/?src=https%3A%2F%2Fkrebsonsecurity.com%2Ffeed%2F), not with MattermostRSS.

**Comment by alecisec** [comment]
I see to be getting it on various feeds - is this at all helpful? https://stackoverflow.com/questions/6728329/hexadecimal-value-0x1f-is-an-invalid-character-line-1-position-1

**Comment by alecisec** [comment]
or this perhaps? https://stackoverflow.com/questions/11182729/hexadecimal-value-0x1f-is-an-invalid-character

**Comment by alecisec** [comment]
I have managed to find the offending feed - it's https://krebsonsecurity.com/feed/ not Hunt's as I'd originally thought, it was because the log 'header' info is displayed when a feed is read successfully, and not when it fails, so I was under the impression that whichever feed I had above Kreb's in my config was the one causing the invalid character errors.

**Comment by PromoFaux** [comment]
:)

![image](https://user-images.githubusercontent.com/1998970/31375597-02c8c30e-ad9a-11e7-893e-05ea69ecedb2.png)

**Comment by alecisec** [comment]
Somehow I missed that response, thanks!
